import type { ExerciseDraft, MuscleGroup } from "../core/domain/exercise";
import type { Seconds } from "../core/domain/primitives";

const compoundRest = 120 as Seconds;
const accessoryRest = 90 as Seconds;
const isolationRest = 60 as Seconds;
const coreRest = 45 as Seconds;

const exercise = (
  name: string,
  primaryMuscles: readonly MuscleGroup[],
  defaultRestSeconds: Seconds,
  secondaryMuscles: readonly MuscleGroup[] = [],
  notes?: string,
): ExerciseDraft => ({
  name,
  primaryMuscles,
  ...(secondaryMuscles.length === 0 ? {} : { secondaryMuscles }),
  defaultRestSeconds,
  ...(notes === undefined ? {} : { notes }),
});

export const baseExercises: readonly ExerciseDraft[] = [
  exercise("Deadlift", ["hamstrings", "glutes"], compoundRest, ["back"]),
  exercise("Sumo Deadlift", ["glutes", "hamstrings"], compoundRest, ["quadriceps"]),
  exercise("Good Morning", ["hamstrings", "glutes"], accessoryRest, ["back"]),
  exercise("Cable Deadlift", ["glutes", "hamstrings"], accessoryRest),
  exercise("Standing Hip Thrust", ["glutes"], accessoryRest, ["hamstrings"]),
  exercise("Hip Thrust", ["glutes"], compoundRest, ["hamstrings"]),
  exercise("Hyperextension", ["glutes", "hamstrings"], accessoryRest, ["back"]),
  exercise("Squat", ["quadriceps", "glutes"], compoundRest, ["hamstrings"]),
  exercise("Sumo Squat", ["quadriceps", "glutes"], compoundRest, ["adductors"]),
  exercise("Sissy Squat", ["quadriceps"], accessoryRest),
  exercise("Leg Press", ["quadriceps", "glutes"], compoundRest, ["hamstrings"]),
  exercise("Leg Extension", ["quadriceps"], isolationRest),
  exercise("Leg Curl", ["hamstrings"], isolationRest),
  exercise("Prone Leg Curl", ["hamstrings"], isolationRest),
  exercise("Standing Leg Curl", ["hamstrings"], isolationRest),
  exercise("Lunge", ["quadriceps", "glutes"], accessoryRest, ["hamstrings"]),
  exercise("Walking Lunge", ["quadriceps", "glutes"], accessoryRest, ["hamstrings"]),
  exercise("Static Lunge", ["quadriceps", "glutes"], accessoryRest, ["hamstrings"]),
  exercise("Side-to-Side Lunge", ["quadriceps", "glutes"], accessoryRest, ["adductors"]),
  exercise("Step Up", ["quadriceps", "glutes"], accessoryRest, ["hamstrings"]),
  exercise("Bulgarian Split Squat", ["quadriceps", "glutes"], accessoryRest, ["hamstrings"]),
  exercise("Quadruped Kickback", ["glutes"], isolationRest),
  exercise("Standing Kickback", ["glutes"], isolationRest),
  exercise("Quadruped Hip Extension", ["glutes"], isolationRest),
  exercise("Hip Abduction", ["abductors"], isolationRest, ["glutes"]),
  exercise("Hip Adduction", ["adductors"], isolationRest),
  exercise("Crab Walk", ["abductors"], isolationRest, ["glutes"]),
  exercise("Shoulder Press", ["shoulders"], compoundRest, ["triceps"]),
  exercise("Arnold Press", ["shoulders"], accessoryRest, ["triceps"]),
  exercise("Front Raise", ["shoulders"], isolationRest),
  exercise("Lateral Raise", ["shoulders"], isolationRest),
  exercise("Rear Delt Fly", ["shoulders"], isolationRest, ["back"]),
  exercise("Upright Row", ["shoulders"], accessoryRest, ["traps"]),
  exercise("Around the World", ["shoulders"], isolationRest),
  exercise("Plate Rotation", ["shoulders"], isolationRest),
  exercise("Front Raise with Twist", ["shoulders"], isolationRest),
  exercise("Front Raise with Wrist Twist", ["shoulders"], isolationRest),
  exercise("Lateral Raise Isometric", ["shoulders"], isolationRest),
  exercise("Lateral Raise to Side", ["shoulders"], isolationRest),
  exercise("Shoulder Press with Pause", ["shoulders"], accessoryRest, ["triceps"]),
  exercise("Triceps Overhead Extension", ["triceps"], isolationRest),
  exercise("Triceps Kickback", ["triceps"], isolationRest),
  exercise("French Press", ["triceps"], isolationRest),
  exercise("Cable Triceps Extension", ["triceps"], isolationRest),
  exercise("Dip", ["triceps", "chest"], accessoryRest, ["shoulders"]),
  exercise("Pull Up", ["back"], compoundRest, ["biceps"]),
  exercise("Chin Up", ["back", "biceps"], compoundRest),
  exercise("Lat Pulldown", ["back"], compoundRest, ["biceps"]),
  exercise("Close-Grip Lat Pulldown", ["back"], compoundRest, ["biceps"]),
  exercise("Wide-Grip Lat Pulldown", ["back"], compoundRest, ["biceps"]),
  exercise("Single-Arm Lat Pulldown", ["back"], accessoryRest, ["biceps"]),
  exercise("Bent-Over Row", ["back"], compoundRest, ["biceps"]),
  exercise("Supinated Bent-Over Row", ["back"], compoundRest, ["biceps"]),
  exercise("Single-Arm Dumbbell Row", ["back"], accessoryRest, ["biceps"]),
  exercise("Seated Row", ["back"], compoundRest, ["biceps"]),
  exercise("Pullover", ["back"], accessoryRest, ["chest"]),
  exercise("Face Pull", ["shoulders"], isolationRest, ["back", "traps"]),
  exercise("Pull Apart", ["shoulders"], isolationRest, ["back"]),
  exercise("Biceps Curl", ["biceps"], isolationRest, ["forearms"]),
  exercise("Hammer Curl", ["biceps"], isolationRest, ["forearms"]),
  exercise("Preacher Curl", ["biceps"], isolationRest, ["forearms"]),
  exercise("Seated Biceps Curl", ["biceps"], isolationRest, ["forearms"]),
  exercise("Alternating Biceps Curl", ["biceps"], isolationRest, ["forearms"]),
  exercise("Biceps Curl Isometric", ["biceps"], isolationRest, ["forearms"]),
  exercise("Barbell Curl", ["biceps"], isolationRest, ["forearms"]),
  exercise("Bench Press", ["chest"], compoundRest, ["triceps", "shoulders"]),
  exercise("Incline Bench Press", ["chest"], compoundRest, ["triceps", "shoulders"]),
  exercise("Chest Press", ["chest"], compoundRest, ["triceps", "shoulders"]),
  exercise("Chest Fly", ["chest"], isolationRest, ["shoulders"]),
  exercise("Pec Deck", ["chest"], isolationRest, ["shoulders"]),
  exercise("Push Up", ["chest"], accessoryRest, ["triceps", "shoulders"]),
  exercise("Incline Push Up", ["chest"], accessoryRest, ["triceps", "shoulders"]),
  exercise("Decline Push Up", ["chest"], accessoryRest, ["triceps", "shoulders"]),
  exercise("Abdominal Exercise", ["abdominals"], coreRest),
  exercise("Plank", ["abdominals"], coreRest),
];
