services:
  train-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run
